# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ${GOROOT}/src/Make.inc

TARG=hjoin
GOFILES=\
	main.go\
	client.go\
	user_manager.go\
	internal-connection.go\
	line.go\
	util.go\
	term_input.go\
	term.go

include ${GOROOT}/src/Make.cmd
